disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - force_unwrapping
  - implicit_return
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument

included:
  - PropHub

excluded:
  - PropHubTests
  - PropHubUITests
  - .build
  - DerivedData

force_cast: error
force_try: error
force_unwrapping: error

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - i

reporter: "xcode"
